### ISSUE TITLE
santa.simulator.selectors.TestSelectors fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by cswarth** [santa-dev/santa-sim#4]
```
$ java -cp dist/santa.jar santa.simulator.selectors.TestSelectors
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at santa.simulator.selectors.TestSelectors.testSelector(TestSelectors.java:63)
        at santa.simulator.selectors.TestSelectors.<init>(TestSelectors.java:41)
        at santa.simulator.selectors.TestSelectors.main(TestSelectors.java:73)
```
Somewhere along the line, possibly as part of dynamic population size experiments,  `santa.simulator.selectors.TestSelectors` was broken.   

The code calls `selector.selectParents` to select a single offspring, then accesses the list of offspring as if an entire population had been selected.

```
			selector.selectParents(population, selected, 1);
			for (int i = 0; i < popSize; i++) {
				selections[selected.get(i)] ++;
			}
```

I think the fix might be to pass `popSize` to `selector.selectParents` instead of `1`, i.e.

```
			selector.selectParents(population, selected, popSize);
			for (int i = 0; i < popSize; i++) {
				selections[selected.get(i)] ++;
			}
```

That seems to work.

**Comment by cswarth** [comment]
Continuous integration build at https://app.wercker.com/cswarth/santa-sim/runs
runs all unit tests.  `santa.simulator.selectors.TestSelectors` is currently passing.
